ALTER TABLE ALUGUEL DROP CONSTRAINT CLIENTE_ALUGUEL_FK;
ALTER TABLE ALUGUEL DROP CONSTRAINT LIVRO_ALUGUEL_FK;
ALTER TABLE ALUGUEL DROP CONSTRAINT FUNCIONARIO_ALUGUEL_FK;

DROP TABLE CLIENTE;
DROP TABLE FUNCIONARIO;
DROP TABLE ALUGUEL;
DROP TABLE LIVRO;

DROP SEQUENCE ALUGUEL_COD_EMPRESTIMO_SEQ;
DROP SEQUENCE LIVRO_COD_LIVRO_SEQ;

CREATE TABLE FUNCIONARIO (
                MATRICULA VARCHAR(11) NOT NULL,
                NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
		        TELEFONE_FUNCIONARIO VARCHAR(11) NOT NULL,
                CONSTRAINT FUNCIONARIO_pk PRIMARY KEY (MATRICULA)
);


CREATE TABLE LIVRO (
                COD_LIVRO INTEGER NOT NULL,
                NOME_LIVRO VARCHAR(100) NOT NULL,
                EDITORA VARCHAR(100) NOT NULL,
                GENERO VARCHAR(100) NOT NULL,
                CONSTRAINT LIVRO_pk PRIMARY KEY (COD_LIVRO)
);


CREATE TABLE CLIENTE (
                CPF_CLIENTE VARCHAR(11) NOT NULL,
                NOME_CLIENTE VARCHAR(100) NOT NULL,
		        TELEFONE_CLIENTE VARCHAR(11) NOT NULL,
                CONSTRAINT CLIENTE_pk PRIMARY KEY (CPF_CLIENTE)
);


CREATE TABLE ALUGUEL (
                COD_EMPRESTIMO INTEGER NOT NULL,
                COD_LIVRO INTEGER NOT NULL,
                CPF_CLIENTE VARCHAR(11) NOT NULL,
                DATA_EMPRESTIMO DATE NOT NULL,
                DATA_DEVOLUCAO DATE,
                MATRICULA VARCHAR(11) NOT NULL,
                CONSTRAINT ALUGUEL_pk PRIMARY KEY (COD_EMPRESTIMO)
);

CREATE SEQUENCE ALUGUEL_COD_EMPRESTIMO_SEQ;
CREATE SEQUENCE LIVRO_COD_LIVRO_SEQ;

ALTER TABLE ALUGUEL ADD CONSTRAINT FUNCIONARIO_ALUGUEL_fk
FOREIGN KEY (MATRICULA)
REFERENCES FUNCIONARIO (MATRICULA)
NOT DEFERRABLE;

ALTER TABLE ALUGUEL ADD CONSTRAINT LIVRO_ALUGUEL_fk
FOREIGN KEY (COD_LIVRO)
REFERENCES LIVRO (COD_LIVRO)
NOT DEFERRABLE;

ALTER TABLE ALUGUEL ADD CONSTRAINT CLIENTE_ALUGUEL_fk
FOREIGN KEY (CPF_CLIENTE)
REFERENCES CLIENTE (CPF_CLIENTE)
NOT DEFERRABLE;
