SELECT A.COD_EMPRESTIMO
      ,A.COD_LIVRO
      ,L.NOME_LIVRO as Livro
      ,A.CPF_CLIENTE
      ,C.NOME_CLIENTE as Cliente
      ,F.NOME_FUNCIONARIO as Funcionario
      ,A.MATRICULA AS Matrucula_funcionario
      ,L.EDITORA
      ,L.GENERO
      ,C.TELEFONE_CLIENTE
      ,A.DATA_EMPRESTIMO
      ,(A.DATA_EMPRESTIMO + 30) as DATA_DEVOLUCAO
      ,F.TELEFONE_FUNCIONARIO
FROM  ALUGUEL A    
INNER JOIN LIVRO          L  ON L.COD_LIVRO    = A.COD_LIVRO
INNER JOIN CLIENTE        C  ON C.CPF_CLIENTE  = A.CPF_CLIENTE
INNER JOIN FUNCIONARIO    F  ON F.MATRICULA    = A.MATRICULA
ORDER BY A.COD_EMPRESTIMO;